version: "3.8.10"

services:
  db:
    container_name: postgres_db
    image: postgres:12
    env_file: .env
    ports:
      - 5434:5432
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
        ]
      interval: 5s
      timeout: 2s
      retries: 5

  migrations:
    build: .
    command: python manage.py migrate
    depends_on:
      db:
        condition: service_healthy

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    stdin_open: true
    tty: true
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully

  celery:
    restart: always
    build:
      context: .
    command: celery -A _challenge_dev worker -l info
    volumes:
      - .:/django_app
    environment:
      - CELERY_BROKER_URL=amqp://guest@rabbitmq:5672//
    env_file:
      - ./.env
    depends_on:
      - rabbitmq
    links:
      - rabbitmq

  rabbitmq:
    container_name: "rabbitmq"
    image: rabbitmq:3-management-alpine

    ports:
      - 5672:5672
      - 15672:15672
